### ISSUE TITLE
Control Bus out?

### ISSUE THREAD

**Issue by gytisgreitai** [andrew-bolin/pi_hifi_ctrl#10]
So we have an in communication for controlling Cambridge Audio. But there is also an out port, do you know if it's possible to hook into it, and know for example when the volume changes?

**Comment by andrew-bolin** [comment]
I can't remember for sure, but it's possible that all commands that come in
via the remote control come out that port too.

But when you press buttons or use the volume knob on the front panel, no
signal will be emitted.

**Comment by gytisgreitai** [comment]
ok, thanks:) was more interested in volume knob events...
