### ISSUE TITLE
CA Azur840a

### ISSUE THREAD

**Issue by kovaga** [andrew-bolin/pi_hifi_ctrl#11]
Thanks for a great work. 
The codes for Azur840a are a bit different, here is the map.

cmd = {
        'source1': 4,
        'source2': 5,
        'source3': 3,
        'source4': 1,
        'source5': 2,
        'source6': 0,
        'source7': 6,
        'source8': 7,
        'tapemon': 7,
        'vol-': 17,
        'vol+': 16,
        'volup': 17,
        'voldown': 16,
        'mute': 13,
        'bright': 18,
        'source+': 8,
        'source-': 9,
        'sourcenext': 8,
        'sourceprev': 9,
        'muteon': 50,
        'muteoff': 51,
        'ampon': 14,
        'ampoff': 15,
        'spkselect': 20
        }

#       'clipoff': 21,   # enters the Balance mode.

**Comment by andrew-bolin** [comment]
Thanks, I have added support for this :)
