### ISSUE TITLE
Raspberry Pi Pico W

### ISSUE THREAD

**Issue by majo44** [andrew-bolin/pi_hifi_ctrl#14]
Hi, 
Firstly, nice work, I was looking for the any info how the Control Bus works for the CA amplifiers, and your solution showed me the way.

So I have CX61, and Raspberry Pi Pico.
I am able to communicate with amplifiers through RS232 , by that I'm able to turn on/off, select source as is in the spec https://techsupport.cambridgeaudio.com/hc/en-us/articles/360012981057-RS232-protocol-for-CXA61-CXA81
The problem is volume +/- as this is not supported by the RS232 interface (sic!)
The only way is to use IR or Control Bus.

Your code is nice but is using Raspberry Pi api which is not available on Raspberry Pi Pico.
I found there is a implementation of RC5 protocol for micropython, TX is here: https://github.com/peterhinch/micropython_ir/blob/master/ir_tx/philips.py.

There is transmit method https://github.com/peterhinch/micropython_ir/blob/master/ir_tx/__init__.py#L80
That method is taking two args _addr_ and _data_ and I'm not sure what I should post there.

1. How to convert your [codes](https://github.com/andrew-bolin/pi_hifi_ctrl/blob/master/cec_stream.py#L24) to _addr_ and _data_ ? I found also something like https://github.com/tmick0/cec2rs232/blob/master/cec2rs232/driver/cambridge_cxa61.py#L105 
2. You think will be save to have shared ground for rs and CB in?

I know that you are no longer support that project, but maybe you can help ?
Best regards.

**Comment by andrew-bolin** [comment]
I haven't looked at the RS232 interface spec (or your other links, sorry),
but the RC5 commands are all sent to the same 'system', which is 16
https://github.com/andrew-bolin/pi_hifi_ctrl/blob/master/cec_stream.py#L21

So my guess would be: address = 16, and data = command. But that's just a
guess :)

**Comment by majo44** [comment]
Thx for help.
Indeed, 16 is address and commands as data works nice.
Only one difference is that I do not using the Ctrl Bus In input in my CXA 61 but the dedicated Ir Input.
![image](https://user-images.githubusercontent.com/2294352/216838621-11d36d1c-14f7-473c-91f7-8518975a8b99.png)
Everything works almost perfectly. Almost as not always the command send from RP is handled by device, so sometimes I have to repeat the signal. 
Many thanks.
