### ISSUE TITLE
Any tips for troubleshooting?

### ISSUE THREAD

**Issue by gytisgreitai** [andrew-bolin/pi_hifi_ctrl#4]
Hi,

thanks for the library. Do you have any tips how to troubleshoot it? 

I have rpi 3 b+. I've wired rca cable main to gpio pin4 and shield to ground. Installed library, launched gpiod but it does not seem to work. I just hear a short "hiss" sound when i send commands, but nothing happens

The amplier is 640A and on the back it has YN 640A V2.0-S EU. So I guess it's v2 version which should be supported? The cable is plugged in into Control Bus In .

**Comment by gytisgreitai** [comment]
ok, that "hiss" only happens when the audio source is raspberry pi (via aux), and after that "hiss" the audio dies and i have to reboot the pi. If I test command when sound is comming from other source (av) nothing happens at all.

**Comment by andrew-bolin** [comment]
Hi there!

Can you send me a copy/paste of what terminal commands you're running (or a
screenshot)  and some pictures of your setup?
From your description the wiring seems OK, but best to confirm with a
picture.
(This is the pin you should wire to, Raspberry Pi numbering is VERY
confusing: https://pinout.xyz/pinout/pin7_gpio4# )

You can email me directly if github doesn't work:
[redacted]

Your amplifier should definitely work. Mine is the 540v2, they're almost
identical.

-- Andrew.

**Comment by gytisgreitai** [comment]
```
osmc@osmc:~/pi_hifi_ctrl$ ./ca_amp_ctrl.py ampon
Sending 'ampon' command to pin 4
osmc@osmc:~/pi_hifi_ctrl$ ./ca_amp_ctrl.py ampoff
Sending 'ampoff' command to pin 4
osmc@osmc:~/pi_hifi_ctrl$ ./ca_amp_ctrl.py vol+
Sending 'vol+' command to pin 4
osmc@osmc:~/pi_hifi_ctrl$ ./ca_amp_ctrl.py aux
Sending 'aux' command to pin 4
osmc@osmc:~/pi_hifi_ctrl$
```
Wiring - black (shield) to the ground, white (main) to gpio4
![rpi-wire](https://user-images.githubusercontent.com/1690228/49747896-1237f900-fcad-11e8-9ef6-d0076294eaad.jpg)
![av-bus](https://user-images.githubusercontent.com/1690228/49747897-1237f900-fcad-11e8-888f-0f1e7a4a3919.jpg)

**Comment by andrew-bolin** [comment]
Wiring looks ok. You could twist your white & black wires together, but it really shouldn't matter at these frequencies. I use pin 9 for ground, but again I can't imagine that makes any difference whatsoever.

A couple of things come to mind - make sure pigpiod is running, this command should show 2 rows (ignore the one for grep):
`ps -ef | grep pigpiod`

Although I would expect you'd see an error message if that was the problem. (Sorry, don't have my pi set up at the moment so I can't confirm for you)

Do you have an oscilloscope, or multimeter?
If you can measure the voltage across your black & white wire before/during/after running a command, it may give some clue.

Try a command with a high repeat number to get a decently-long signal to measure:

`./ca_amp_ctrl.py --repeat 99 ampoff`

This should hopefully give a voltage something around 1.6V. You could try this first with your cable connected, then with it disconnected, just in case something strange is going on inside your amp.

If you have a frequency mode on your meter, that's worth a look too, it should be some hundreds of Hz.

**Comment by andrew-bolin** [comment]
> "hiss" only happens when the audio source is raspberry pi (via aux), and after that "hiss" the audio dies and i have to reboot the pi

This sounds like there is probably some conflict between pigpiod and other software running on the pi.

Can you stop the other software or try a fresh install of [DietPi](http://dietpi.com/) or Raspbian ?

**Comment by gytisgreitai** [comment]
Yep, seems to the problem with OSMC image. Works fine on Raspbian (except the `--repeat` for `vol+` or `vol-`). Thanks.

**Comment by gytisgreitai** [comment]
Ok, figured it out. had to start pigpiod with -t option : `-t 0`.
