### ISSUE TITLE
Missing info

### ISSUE THREAD

**Issue by mogin99** [andrew-bolin/pi_hifi_ctrl#5]
Hi you asked what clipping was, it’s when the audio signal is too loud and a theoretical sine wave gets ‘clipped’. This represents too fast a transient for the speaker coil, resulting in damage. It’s the way speakers get ‘blown’. The CA firmware detects clipping and deals with it. You want to leave this on.

I’ve never used a pi before and find myself needing to write to the CA control bus.
No idea where to start. I don’t even know how Control Bus works. Do you have any pointers?

**Comment by andrew-bolin** [comment]
Hi there,
Ahh, so "clipoff" would turn off the clipping detection / protection? Makes sense. I knew it had clipping detection, didn't realise you could turn it off!

Control Bus is quite simple, it's pretty much infra-red remote signals, minus the 36kHz modulation.
See here: https://en.wikipedia.org/wiki/RC-5
Instead of 36kHz square wave, just leave the pin high for the 889μs.

**Comment by mogin99** [comment]
Thanks very much. I’ll pretend to know what it means but I’m sure I can work it out. Last time I wrote computer program was on a BBC micro.

My end game is to pickup the 12V trigger out from an AV receiver and use it to get a Pi turn on the amp, pause, set to A1, volume at 50%. Last bit is possibly not doable!

You also asked about ‘Dimmer’. This is just the display brightness each time it’s ‘pressed’ it goes UP in increments and then resets back to lowest.

**Comment by andrew-bolin** [comment]
OK, well, you can certainly use my software to do that. Previous post was assuming you wanted to do it yourself without a Pi...

You'll want to convert the 12V trigger into a 3.3V signal for the Pi - easily done with a resistor & zener diode, or two resistors, or a transistor circuit, or a level converter module, or a relay, or ...

Then you just need to make a small script that can monitor an input. You could check out the pigpio documentation for that, or search around - there must be examples!

You'll want this script to run a series of commands something like:

`ca_amp_ctrl.py ampon`
`ca_amp_ctrl.py aux`
etc.  (one command for each different button you'd press on the remote)

Unfortunately you can't do "set volume to 50%" - there is no feedback of current volume level.

I'd suggest you start out by just getting the commands to run manually, then add the automation once it's all working. One of the other "issue" threads here has some photos of how to do the wiring.

**Comment by mogin99** [comment]
Thanks so much :)
I will buy a pi shortly. I can just do a loop for the audio to send it all the way to zero and then back up to half way by increments, should work :)

**Comment by mogin99** [comment]
Hi again,
Got all my toys. The local parts shop also sold me a step down to get to 3V input for the Pi.

My amp has 8 inputs, 4 analogue and 4 digital.... any idea how I figure out which command I need to send down control bus to get Analogue #1?

Thanks
Ben

**Comment by andrew-bolin** [comment]
Which model amp?

First analog input is probably the "cd" command.
Try these and see what they do: aux, av, cd, dvd, tapemon, tuner

**Comment by mogin99** [comment]
Hey there! CXA60.

I’ll try your suggestions. Thanks!

Only got as far as ‘hello world’ but hey... progress :)
