### ISSUE TITLE
CXA60 Mismatched IR Codes

### ISSUE THREAD

**Issue by julescole** [andrew-bolin/pi_hifi_ctrl#8]
Hey, great little project. I notice a few other people have tried and failed to make this work with the CXA60. I have found that using your code, sending IR codes 110 and 174 turn the amp on and 111 and 175 turn the amp off; this is confusing as the Cambridge audio documentation says codes 14 and 15 (as per your original code) should work, but they don't. This has made me think that maybe there is an encoding problem with how they're sent? Just a thought. 

I'd really like to be able to get more use from this, but so far i've only managed to make volume, mute and power work.

**Comment by andrew-bolin** [comment]
Hey there, thanks for the info and nice work in getting the CXA60 going!

I'll see if I can look into it a bit later - feel free to give me a nudge
again in a couple of weeks.
Interesting to note that 110 in binary is 0110 1110, and 14 is 1110, so
there very well could be something funny going on with the RC5 encoding.

**Comment by julescole** [comment]
Amazing, thank you. 

It's probably worth adding, that I added your code from Issue https://github.com/andrew-bolin/pi_hifi_ctrl/issues/3

```  
        if (cmd<64):
                field = 1
        else:
                field = 0
        RC5_START = 0b100 + (0b010 * field)
```

**Comment by julescole** [comment]
Just been having a further play with this. It appears that the on and off commands work for all codes in multiples of 64 - if that's of any help. So for example the 'on' function is successfully triggered when sending the following codes : 110,174,238,302,366,430 and the 'off' function is succesfully triggered with the following: 111,175,239,303,367,431. This only seems to happen with the on/off functions, the volume functions only work with their codes 16/17. I'm not an expert in binary, so any help gratefully appreciate :)

**Comment by julescole** [comment]
@andrew-bolin  Just giving the requested nudge ;) I'd really like to finish my project, but i'm struggling a bit with binary. Thanks in advance!

**Comment by andrew-bolin** [comment]
Hey, sorry for taking so long to get back. I no longer have a setup where I can do any real hardware testing on this :(

I see you mentioned adding some code to the RC5_START, but the code currently on github already has that change incorporated. Have you made any other changes? (you could run `git diff` perhaps? or upload your full project to your github page?)

I'll have a look through the code today and see if anything jumps out...

**Comment by julescole** [comment]
Thanks for the reply. OK, i can try and tackle it on my own. I removed that bit of code in the end, as it didn't seem to change the functionality. So it's pretty much your code, but with the ir codes changed to reflect the new ones i found that worked for my amp. I just wish I could get the channel switching and speaker selection to work. Maybe i just need to do it via IR instead, if the control bus has been limited. I just wondered if there was some flawed logic in how the codes were encoded that was causing the problem, but maybe not.

**Comment by andrew-bolin** [comment]
Does **46** (in binary: 101110, same as the lower 6 bits of 110) also work for power on?

As you've discovered, adding 64 makes no difference to the code that's actually sent out on the wire, only the lower 6 bits are used (plus 1 bit in the header which is used as a 'backwards' 7th bit, and RC-5 doesn't permit numbers greater than 127 but my code doesn't check for that)

One thing I have skipped, from the RC-5 spec, is a bit that's meant to toggle for each message. Can you test if sending 1,2,3,4 consecutive volume commands actually move the volume by 4 different sized increments? It worked fine on my 540 amp, but maybe cambridge changed their firmware...

e.g. `ca_amp_ctrl.py --repeat 3 vol+`

another thing to test would be changing the CA_RC5_SYS variable to another number (17?), and see if it still responds or if any behaviour changes.

**Comment by julescole** [comment]
Thanks Andrew

46 doesn't work to turn on the app, it only works of multiples of 64 starting from 110. 

If i send consecutive commands (with --repeat), it works as long as the commands aren't fired too close together. Because of this, i added `time.sleep(0.5);` in between issuing each command in the repeat for loop. This seems to make it work consistently. 

Changing CA_RC5_SYS to 17 makes none of the commands work.

**Comment by andrew-bolin** [comment]
How bizarre!
I think to really understand what's going on we would need someone to get the IR codes really used by the remote control, and maybe testing the amp with an external wired IR receiver to see if all buttons work via the port...

The repeat issue might be fixed with the code below (replace the whole build _rc5 function), but sorry without real hardware to experiment with I think this is pretty much the end of the road. 

*EDIT: can't get the code to look nice here, I've added a branch: https://github.com/andrew-bolin/pi_hifi_ctrl/tree/andrew-bolin-toggle *

I think you already tried looping over all possible codes to see if anything else happens? Looping over all possible system and command codes is only 32*128 items, about half an hour at one try every half second... (of course, it might be hard to tell if the commands have worked when there's things like "next input" and "previous input" close together...)

**Comment by julescole** [comment]
Thanks Andrew for your time on this. I put in the toggle addition, you would need to call the build_rc5 on each repeat for it to work, i think. However, it didn't seem to have any affect on my system. 

I also looped over all codes on every system code, but unfortunately with no luck. I think i'll need to add an IR emitter to get it to work fully. 

Thank again.

**Comment by andrew-bolin** [comment]
> you would need to call the build_rc5 on each repeat for it to work, i think

Quite true. Forgot about my over-eager optimisation. Made another mod to that branch to fix it.

Seems like you're at the end of the road without some hardware debug tools :(

**Comment by andrew-bolin** [comment]
@julescole - only 2.5 years late, but I've finally added the CXA60 codes to the main program...

**Comment by edwinchoi** [comment]
And many years later... CXA60 uses a different system code for powering on/off the unit -- `system = 25, command = 14`. At least for IR codes.

I don't know if this is something they changed over the years, but I'm guessing they use a different system code to avoid conflicts with other remotes that use system = 16 (see table 11 of wiki on [RC5](https://en.wikipedia.org/wiki/RC-5)).
